### ISSUE TITLE
random error with random agent

### ISSUE THREAD

**Issue by luvf** [MarvinLer/pypownet#27]
I created this agent.
And I have the same error as previously (i created another bug tracking, because it is a totally different  input) but ti append randomly in time, (low rate  with p near 1

class TrainerAgent(Agent):
    """ The template to be used to create an agent: any controler of the power grid is expected to be a daughter of this
    class.
    """

    def __init__(self, environment):
        """Initialize a new agent."""
        self.agent = GreedySearch(environment)
        self.randoma = RandomNodeSplitting(environment)
        self.actions = list()
        self.environment = environment

    def act(self, observation):
       
        if np.random.rand() < 0.3 :
            action = self.agent.act(observation)
            self.actions.append( (observation.as_array(), action.as_array())) 
        else :
            action = self.randoma.act(observation)
        return action

the errorTraceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/to/pypownet/main.py", line 63, in <module>
    main()
  File "/home/to/pypownet/main.py", line 58, in main
    final_reward = runner.loop(iterations=args.niter)
  File "/home/to/pypownet/runner.py", line 111, in loop
    (obs, act, rew) = self.step()
  File "/home/to/pypownet/runner.py", line 80, in step
    action = self.agent.act(self.last_observation)
  File "/home/to/pypownet/agent.py", line 592, in act
    action = self.agent.act(observation)
  File "/home/to/pypownet/agent.py", line 232, in act
    reward_aslist = self.environment.simulate(action, do_sum=False)
  File "/home/to/pypownet/environment.py", line 611, in simulate
    observation, reward_flag, done = self.game.simulate(to_simulate_action)
  File "/home/to/pypownet/game.py", line 606, in simulate
    simulated_obs, flag, done = self.step(action, _is_simulation=True)
  File "/home/to/pypownet/game.py", line 556, in step
    self._compute_loadflow_cascading()
  File "/home/to/pypownet/game.py", line 370, in _compute_loadflow_cascading
    self.grid.compute_loadflow(fname_end='_cascading%d' % depth)
  File "/home/to/pypownet/grid.py", line 244, in compute_loadflow
    output, loadflow_success = self.__vanilla_loadflow_backend_callback(fname_end=fname_end)
  File "/home/to/pypownet/grid.py", line 218, in __vanilla_loadflow_backend_callback
    output, loadflow_success = function(self.mpc, self.loadflow_options, pprint, fname)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/rundcpf.py", line 26, in rundcpf
    return runpf(casedata, ppopt, fname, solvedcase)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/runpf.py", line 99, in runpf
    ref, pv, pq = bustypes(bus, gen)
  File "/usr/lib/python3.7/site-packages/PYPOWER-5.1.4-py3.7.egg/pypower/bustypes.py", line 47, in bustypes
    ref[0] = pv[0]      # use the first PV bus

**Comment by MarvinLer** [comment]
Yes, this is the same bug than #26, will look into it shortly.
