### ISSUE TITLE
Echec du mode render

### ISSUE THREAD

**Issue by vincentbarbesant** [MarvinLer/pypownet#35]
La commande `python -m pypownet.main --agent DoNothing -r` donne l'erreur suivante :
 
`File "/home/barbesantvin/challenge/pypownet/pypownet/renderer.py", line 431, in draw_surface_diagnosis self.data['number_unavailable_nodes'], self.data['max_number_isolated_loads'],`
`KeyError: 'number_unavailable_nodes'
`

Le rendu et le calcul sont bloqués à la première itération.

**Comment by MarvinLer** [comment]
Hi thanks for the feedback
This should be fixed in 20c6b830f88d47bb27a2c9f5228a35376f717824, can you pull ? Is it okay now ?

ML

**Comment by vincentbarbesant** [comment]
I got a new error now : 
`Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/barbesantvin/challenge/pypownet/pypownet/main.py", line 60, in <module>
    main()
  File "/home/barbesantvin/challenge/pypownet/pypownet/main.py", line 54, in main
    runner = Runner(env, agent, args.render, args.verbose, args.vverbose, args.parameters, args.level, args.niter)
  File "/home/barbesantvin/challenge/pypownet/pypownet/runner.py", line 70, in __init__
    self.environment.render()
  File "/home/barbesantvin/challenge/pypownet/pypownet/environment.py", line 853, in render
    self.game.render(self.last_rewards, game_over=game_over)
  File "/home/barbesantvin/challenge/pypownet/pypownet/game.py", line 1005, in render
    game_over=game_over, cascading_frame_id=cascading_frame_id)
  File "/home/barbesantvin/challenge/pypownet/pypownet/renderer.py", line 921, in render
    max_number_isolated_loads, max_number_isolated_prods)
  File "/home/barbesantvin/challenge/pypownet/pypownet/renderer.py", line 873, in _update_topology
    self.draw_surface_nodes_headers(scenario_id, date, cascading_result_frame=cascading_frame_id)
  File "/home/barbesantvin/challenge/pypownet/pypownet/renderer.py", line 172, in draw_surface_nodes_headers
    self.black_bold_font_render('new observation frame'),number_unavailable_lines` 
`NameError: name 'number_unavailable_lines' is not defined
`

**Comment by MarvinLer** [comment]
Fixed in a1a648c238ffad0bec19a1303e08f5688ce071bc, sorry stupid mistake :)
Is it okay now ?

**Comment by vincentbarbesant** [comment]
👍
